kind: CronJob
apiVersion: batch/v1

metadata:
  name: test
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test
              image: test:latest
              env:
                - name: FOO
                  value: "42"
